### ISSUE TITLE
pcre and building clamav: now pcre2

### ISSUE THREAD

**Issue by steb5067** [killdash9/MacClam#3]
Thanks for this very useful script. 

Note that pcre is now frozen at 8.44 and pcre2 is the actively developed branch. This is now recommended as a dependency instead of pcre. Can you update to reflect this?

PS not your issue, but script currently breaks because pcre hasnt updated their certificates and curl borks

**Comment by harens** [comment]
As well as some other changes, I've updated pcre to pcre2 in my fork found [here](https://github.com/harens/MacClam). 

Although there are many benefits to this, I don't know if this fixes your problem since the original script worked for me without breaking.

@killdash9 I'm happy to send a PR to hopefully close this issue if development picks up again.
